name: pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Setup Python.
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies.
        run: pip install -r requirements-dev.txt

      - name: Test with pytest.
        run: pytest -vv
